# This file is dynamically generated

FROM renegare/docker-web-php54

# configure apache
COPY env/etc/httpd/conf.d/app.conf /etc/httpd/conf.d/app.conf

{{#version}}
# install app @todo need to checkout a given hash
RUN git clone https://github.com/renegare/docker-app-sample.git /app
WORKDIR /app
RUN git checkout {{version}}
{{/version}}

EXPOSE 80
